// The DOM shim MUST be the first import: element-js component classes are `class … extends
// HTMLElement`, evaluated at import time, so `HTMLElement` has to exist first. Node evaluates ESM
// imports in source order, so this static top-level import is enough here (no bundler hoisting like
// the Nitro/Nuxt example has to work around).
import "@webtides/element-js-ssr-renderer/dom-shim";
import { elementSSR } from "@webtides/element-js-ssr-renderer/eleventy";

// Two component sources, composed (later wins on a tag clash):
import catalog from "@webtides/element-library/catalog"; // the library ships its own lazy catalog
import localComponents from "./_catalog.js"; // generated by `npm run gen:catalog` (see README)

export default function (eleventyConfig) {
  // Pre-render every element-js custom element authored in the output HTML, at build time.
  // Register it BEFORE any HTML-minifier transform so the minifier (if you add one) sees — and is
  // told to preserve — the `<template shadowrootmode>` this emits.
  eleventyConfig.addTransform(
    "element-ssr",
    elementSSR({ resolve: [catalog, localComponents] }),
  );

  return {
    dir: { input: "src", output: "_site", includes: "_includes" },
    markdownTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
  };
}
