// Generated by @webtides/element-js-ssr-renderer — do not edit by hand.
// Source: directory ./elements (2 components)
// A static, bundler-traceable Catalog. Pass it straight to `resolve` — no wrapper:
//   import catalog from "./catalog.js";
//   elementSSR({ resolve: catalog });

/** @type {import("@webtides/element-js-ssr-renderer").Catalog} */
export default {
  "x-counter": () => import("../elements/x-counter.js"),
  "x-greeting": () => import("../elements/x-greeting.js"),
};
